リザルト画面表示（記録・総記録・称号）
tricore-h-yano/KarateChop pull request #17
Opened 2021-07-29 06:08 UTC by tricore-h-yano

リザルト画面表示（記録・総記録・称号）実装しました。
確認点
Script
・ScoreManager
Prefab
・ScoreManager
確認方法
GameSceneを実行して記録が保持されているか確認
Spaceキーでデータ消去できます。

2021-07-29 06:28 UTC, tricore-as05 requested changes

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/GameToResultScreenChanger.cs
> +        endGameAction += action;
[MUST]
SetResetActionと変数コメント被ってるので変えてください

[Q]
resetAction と呼び出しタイミング一緒なのに追加した理由はなんですか？

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/TileTypeSelector.cs
> +            isGold = true;
[MUST]
isGold = goldTileObjectRoot.activeSelf; とまとめられます

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/ScoreManager.cs
> +    [SerializeField] TextMeshProUGUI nowScoreTextMesh = default;
[nits]
TextMeshじゃなくてTextだけでいいと思います。

あと意味は分かるのですが、こうやってまとめて表示している変数たちは、
題名みたいな感じで一番上に// スコアテキストとかコメントを残してもいい気がします。

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/ScoreManager.cs
> +    [SerializeField] float firstScoreRankThreshold = default;
[nits]
閾値や、下の方にあるconst string達をスクリプタブルオブジェクトでまとめたいですね

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/ScoreManager.cs
> +
[MUST]
余計は空白

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/ScoreManager.cs
> +            Debug.Log("セーブデータ削除");
[MUST]
基本デバッグ用のコードは消してください
また、セーブデータの削除を行いたい場合は、Edit → Clear All PlayerPrefsで消せます

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/ScoreManager.cs
> +        // 割った枚数の評価
[nits]
せっかく細かな関数化をしているのなら、割った枚数の評価と総枚数の評価も関数化したほうが見やすいと思います。

2021-07-29 06:28 UTC, tricore-as05 commented on Assets/MyAssets/Script/ScoreManager.cs
> +
[MUST]
余計な空白

2021-07-29 07:03 UTC, tricore-h-yano commented on Assets/MyAssets/Script/GameToResultScreenChanger.cs
> +        endGameAction += action;
コメント修正しました。
[Q]の返答ですが、タイミングは確かに同じなのですが、リセットが行われる前にカウンターから割った枚数を取得する必要があったので別アクションに登録して必ず先に呼ばれるようにしたいと考え追加しました。

2021-07-29 07:03 UTC, tricore-h-yano commented on Assets/MyAssets/Script/TileTypeSelector.cs
> +            isGold = true;
isGold = goldTileObjectRoot.activeSelf;に修正しました。

2021-07-29 07:04 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +    [SerializeField] TextMeshProUGUI nowScoreTextMesh = default;
Meshを削除し1番上に// スコアテキストというコメントだけ書き足しました。

2021-07-29 07:06 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +    [SerializeField] float firstScoreRankThreshold = default;
スクリプタブルオブジェクトはα提出後、時間があればやりたいと思っています。

2021-07-29 07:06 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +
削除しました。

2021-07-29 07:38 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +            Debug.Log("セーブデータ削除");
削除しました。

2021-07-29 07:38 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +        // 割った枚数の評価
関数化しました。

2021-07-29 07:38 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +
削除しました。

2021-07-29 08:51 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +            Debug.Log("セーブデータ削除");
Editから削除できることを知りませんでした。
デバッグ用コード削除しました。

2021-07-29 08:51 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +        // 割った枚数の評価
関数分けしました。

2021-07-29 08:51 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +
削除しました。

2021-07-29 08:52 UTC, tricore-h-yano commented on Assets/MyAssets/Script/GameToResultScreenChanger.cs
> +        endGameAction += action;
Dictionaryを使ったやり方に変更しました

2021-07-29 08:54 UTC, tricore-as05 approved these changes
LGTM

2021-07-29 09:48 UTC, tricore-t-yui requested changes

2021-07-29 09:48 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +
[nits]
不要な空行

2021-07-29 09:48 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +        if (firstScoreRankThreshold > nowScore)
[MUST]
if文の判定式が冗長かつ分かりづらいので最適化してください

2021-07-29 09:48 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +    const string WhiteBelt = "白帯";
[MUST]
この辺変数名だけ見ても何が何番目のランクか分からないので修正してください

2021-07-29 09:48 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +        string count = nowScore.ToString();
[MUST]
ToStringが不要に乱発されているのと、if elseがもう少し整理できそうなので整理してください。
「count」という名前がローカル変数にしても万能すぎてぱっと見何か分からない

2021-07-29 09:48 UTC, tricore-t-yui commented on Assets/MyAssets/Script/TileTypeSelector.cs
> +    bool isGold = false;
[MUST]
プロパティに統一できる

2021-08-02 03:59 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +
削除しました。

2021-08-02 03:59 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +        if (firstScoreRankThreshold > nowScore)
自分なりに最適化しました。

2021-08-02 04:00 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +    const string WhiteBelt = "白帯";
変数名変更しました。

2021-08-02 04:01 UTC, tricore-h-yano commented on Assets/MyAssets/Script/ScoreManager.cs
> +        string count = nowScore.ToString();
nowScoreText.text = nowScore + Sheet;
この書き方に統一しました。

2021-08-02 04:02 UTC, tricore-h-yano commented on Assets/MyAssets/Script/TileTypeSelector.cs
> +    bool isGold = false;
修正しました。

2021-08-02 05:38 UTC, tricore-t-yui approved these changes
コメントをそれなりに入れたけど一応Approve

2021-08-02 05:38 UTC, tricore-t-yui commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +        gameToResultScreenChanger.SetEndGameAction(PriorityOrder.Normal, action);
[nits]
nitsじゃないけど突っ込みを残しておく
gameToResultScreenChanger.SetEndGameActionが様々なところから呼ばれてわかりづらい
基底クラスの中で呼んでいて隠されているのもあり、スパゲティ推進コードになってる

2021-08-02 05:38 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +    [SerializeField] float firstScoreRankThreshold = default;
[nits]
floatなどの値型は大体想定しているデフォルト値を入れてほしい

2021-08-02 05:38 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +    const string TotalScoreKey = "TotalScore";
[nits]
キーは分かりやすく一か所にまとめたい
string型のものなのでほかのものと混同しやすいのもある
あとstring hashを使いたいところ

2021-08-02 05:38 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +        normalHighScore = PlayerPrefs.GetInt(NormalHighScoreKey);
[nits]
引数でデフォルト値を入れてあげたい

2021-08-02 05:38 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +            normalHighScoreText.text = null;
[Q]
null入っているけどエラー出ない？
空文字じゃなくても大丈夫なのかな…

2021-08-02 05:38 UTC, tricore-t-yui commented on Assets/MyAssets/Script/ScoreManager.cs
> +    const string ScoreRankC = "白帯";
[nits]
修正不要だけど一応。S>A>B>Cというのは変数の名前の世界ではあまり通用しない気がする。
分かるけど。

2021-08-02 05:49 UTC, merged