瓦にめり込んでしまう不具合修正
tricore-h-yano/KarateChop pull request #22
Opened 2021-08-06 05:46 UTC by tricore-h-yano

瓦にめり込んでしまう不具合修正しました。
これに伴いプレイヤーに移動制限つけました。
確認点
Script
・AutoMoverBase
・PlayerController
・PlayerHitChecker
・TileGroupManager
Prefab
・GameCanvas
・PlayerHand
・MoveLimetedPoint
・GameSceneRoot
・TileGroupRoot
確認方法
GameSceneでプレイして瓦の左右から当たりめり込まないか確認

2021-08-06 05:54 UTC, tricore-as05 requested changes

2021-08-06 05:54 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +
[MUST]
たしかUpdateは関数コメントいるはず
あと、この移動制限UpdateじゃなくてStateChangedHandleとかドラッグ中に書けば何とかなりませんか？
Updateはできれば安易に使ってほしくないです

2021-08-06 05:54 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +    [SerializeField] GameObject minMovingLimitPointX = default;
[Q]
これ右下左下に置けば2つの参照だけで済みませんか？

2021-08-06 05:55 UTC, tricore-as07 approved these changes

2021-08-06 05:55 UTC, tricore-as07 commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +    [SerializeField] float maxSpeed = 50.0f;
[Q]
Editor上で調整できるようにSerializeFieldにしていると思われるのですが、
なぜスクリプトで値を変更したのでしょうか？

2021-08-06 05:55 UTC, tricore-as07 commented on Assets/MyAssets/Script/PlayerController.cs
> +    [SerializeField] GameObject minMovingLimitPointX = default;
[nits]
出来れば一つのオブジェクトのポジションとサイズで可動域の制御をしてほしいです。

2021-08-06 06:18 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +
関数コメント追加しました。
Updateで行っている理由としては、TouchScriptがドラッグ中のオブジェクトのポジションを動かしているのですが、おそらく、StateChangedHandleを登録している、Eventよりも後にポジションの更新を行っているみたいでStateChangedHandleの中で呼び出した場合移動制限がうまくいかなかったのでUpdataを使っています。

2021-08-06 06:18 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +    [SerializeField] GameObject minMovingLimitPointX = default;
1つのポイントにして対応しました。

2021-08-06 06:18 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +    [SerializeField] float maxSpeed = 50.0f;
defaultで値を入れておくべきかなと思ったので変更しました。

2021-08-06 06:18 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +    [SerializeField] GameObject minMovingLimitPointX = default;
1つのオブジェクトにして対応しました。

2021-08-06 06:37 UTC, tricore-as05 requested changes
口頭で説明したけど、
縦横上限の取得方法の変更をお願いします。

2021-08-06 06:37 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +
TouchScript固有の移動方法で、移動している箇所がわからないとのことだったので無し

2021-08-10 07:32 UTC, tricore-as05 requested changes

2021-08-10 07:32 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +        float limitedX = Mathf.Clamp(myRectTransform.transform.position.x, -(movingLimitPoint.rect.width / 2.0f) + movingLimitPoint.transform.position.x, (movingLimitPoint.rect.width / 2.0f) + moving
[MUST]
/2.0fは*0.5fに置き換えてください
割り算はコストが高いらしいので

2021-08-10 07:35 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +        float limitedX = Mathf.Clamp(myRectTransform.transform.position.x, -(movingLimitPoint.rect.width / 2.0f) + movingLimitPoint.transform.position.x, (movingLimitPoint.rect.width / 2.0f) + moving
変更しました。

2021-08-10 07:37 UTC, tricore-as05 approved these changes
LGTM

2021-08-10 09:05 UTC, tricore-t-yui approved these changes
LGTM
nits一件

2021-08-10 09:05 UTC, tricore-t-yui commented on Assets/MyAssets/Script/PlayerController.cs
> +        float limitedX = Mathf.Clamp(myRectTransform.transform.position.x, -(movingLimitPoint.rect.width * 0.5f) + movingLimitPoint.transform.position.x, (movingLimitPoint.rect.width * 0.5f) + moving
[nits]
transformってアクセスするだけで重いので、こうやって連発してアクセスするときは変数に保存したほうがよい

2021-08-10 09:11 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +        float limitedX = Mathf.Clamp(myRectTransform.transform.position.x, -(movingLimitPoint.rect.width * 0.5f) + movingLimitPoint.transform.position.x, (movingLimitPoint.rect.width * 0.5f) + moving
1度変数に保存して扱うように修正しました。

2021-08-10 09:11 UTC, merged