プレイヤーのドラッグ速度に応じて瓦が次々に割れていく処理
tricore-h-yano/KarateChop pull request #6
Opened 2021-07-20 07:57 UTC by tricore-h-yano

プレイヤーのドラッグ速度に応じて瓦が次々に割れていく処理を実装しました。
確認点
Script
・AutoMovePlayer
・AutoMoveTileGroup
・PlayerController
・PlayerHitChecker
・TileGroupManager
・TileHitChecker

確認方法
GameScene上に配置している手をドラッグで動かして瓦に当てると割れます  
　→当たった時にプレイヤーのドラッグ速度に応じて瓦が次々に割れるか確認

2021-07-20 08:51 UTC, tricore-as05 requested changes

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +    bool moveFlag;
[MUST]
フラグ系はis~~という命名が基本になるので、この例でいくとisMoveなどにしていただけるといいと思います。

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +    float preMoveSpeed;
[nits]
preというのは大体「前の~~」という意味合いが多いという印象なので、名前を変えたほうがいい気がします。

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +                moveSpeed = maxSpeed;
[MUST]
moveSpeedは変数として保存する必要ないのではないでしょうか？

関数内でfloat moveSpeed = 0;と定義してから使えばいいかと思います。
また、こちらのmoveSpeedが変数としてあるせいで、
preMoveSpeedという命名になってしまっていると感じましたので、
preMoveSpeedをmoveSpeedという違和感のない命名にできるかと思います。

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +public class AutoMovePlayer : MonoBehaviour
[MUST]
クラス名ですが、AutoPlayerMoverの方が適切な気がします

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/AutoMoveTileGroup.cs
> +public class AutoMoveTileGroup : MonoBehaviour
[MUST]
AutoMovePlayerでコメントした箇所と同じような修正箇所がある為、コメントはしませんが修正をお願いします。

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/AutoMoveTileGroup.cs
> +        if (moveFlag)
[nits]
Updateの中身がAutoMovePlayerとまったく同じのように見えるので、まとめれるならまとめたいですね

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +    [SerializeField] GameObject breakPoint = default;
[nits]
命名もコメントもわかりずらいように感じますので、以下のような命名が良いかと思います。

// 瓦が割るためのコライダー
GameObject tileBreakCollider = default;

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +    /// 変形中の処理
[Q]
変形中とは何でしょうか？ドラッグ中ということでしょうか？

もしドラッグ中だったら、Updateでやっているtime++;はここで宣言したほうがいいかと思うのですが

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +    /// キャンセルされた時の処理
[Q]
キャンセルとは何のキャンセルでしょうか？瓦に当たったときという意味でしょうか？

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +        ++time;
[Q]
このtimeは常に計測する必要があるのでしょうか？
ドラッグし始めてからでいいかと思うのですが...

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerHitChecker.cs
> +    public bool AutoMoveFlag { get { return autoMoveFlag; } }
[MUST]
フラグの命名はis~~でお願いします

2021-07-20 08:51 UTC, tricore-as05 commented on Assets/MyAssets/Script/TileGroupManager.cs
> +    {
[nits]
どういう処理なのかのコメントを付けてほしいです

2021-07-20 08:53 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +    bool moveFlag;
isMoveに修正します

2021-07-20 08:53 UTC, tricore-as03 requested changes

2021-07-20 08:53 UTC, tricore-as03 commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +    }
[MUST]
Update関数の中身やクラスのメンバ変数が、AutoMovePlayerとAutoMoveTileGroupとで似ているので、新たにベースクラスを作って、そのクラスを２つのクラスで継承することで処理を共通化したほうがよいと思います。

2021-07-20 08:55 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +                moveSpeed = maxSpeed;
関数内でfloat moveSpeed = 0;と定義して扱う方向で修正します。

2021-07-20 08:55 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +public class AutoMovePlayer : MonoBehaviour
AutoPlayerMoverに変更します。

2021-07-20 08:56 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMoveTileGroup.cs
> +public class AutoMoveTileGroup : MonoBehaviour
AutoTileGroupMoverに変更します

2021-07-20 08:56 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +    /// 変形中の処理
ドラッグ中という意味ですので書き換えておきます

2021-07-20 08:58 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +    /// キャンセルされた時の処理
離した以外で強制的にドラッグが終了したとき＝キャンセルで書いていました。
もう少し詳しく書き直します

2021-07-20 08:59 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +        ++time;
ドラッグ開始時に計測するように変更します

2021-07-20 08:59 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerHitChecker.cs
> +    public bool AutoMoveFlag { get { return autoMoveFlag; } }
修正します

2021-07-20 08:59 UTC, tricore-h-yano commented on Assets/MyAssets/Script/TileGroupManager.cs
> +    {
修正します

2021-07-20 09:00 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +    }
修正します

2021-07-20 09:23 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +    [SerializeField] GameObject breakPoint = default;
GameObject tileBreakColliderに修正しました

2021-07-20 09:25 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMovePlayer.cs
> +    float preMoveSpeed;
クラスに持たせる変数名を
// 受け取った移動速度保存
float receivedMoveSpeed
に変更しmoveSpeedは関数内で使用するようにしました。

2021-07-21 00:28 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMoveTileGroup.cs
> +        if (moveFlag)
継承を使ってまとめました

2021-07-21 00:40 UTC, tricore-as03 requested changes

2021-07-21 00:40 UTC, tricore-as03 commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +    protected void AutoMoveProcess()
[MUST]
それぞれ関数名を書いてください。

2021-07-21 00:40 UTC, tricore-as03 commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +    protected bool isMove;
[MUST]
継承先のクラスで弄らないのであればprivateにしてほうが良いと思います。

2021-07-21 00:47 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +    protected bool isMove;
privateに修正しました。

2021-07-21 00:47 UTC, tricore-h-yano commented on Assets/MyAssets/Script/AutoMoverBase.cs
> +    protected void AutoMoveProcess()
修正します。

2021-07-21 00:49 UTC, tricore-as03 approved these changes
LGTM

2021-07-21 00:50 UTC, tricore-as05 requested changes

2021-07-21 00:50 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +
[MUST]
中身が空なので消しておいてください

2021-07-21 00:50 UTC, tricore-as05 commented on Assets/MyAssets/Script/PlayerController.cs
> +            time = 0.0f;
[MUST]
前回指摘し忘れてて申し訳ないのですが、
ドラッグ中以外でtimeをリセットする必要がある気がします(OnEnableとか、ドラッグが終了した時とか)
そうしないと中途半端にタイムが進んだ状態からカウントが始まってしまう場合があるかと思います。

2021-07-21 01:10 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +
修正します。

2021-07-21 01:11 UTC, tricore-h-yano commented on Assets/MyAssets/Script/PlayerController.cs
> +            time = 0.0f;
ドラッグ終了時とOnEnableに追加しました。

2021-07-21 01:38 UTC, tricore-as05 approved these changes
LGTM

2021-07-21 01:39 UTC, merged